os: osx
language: objective-c
osx_image: xcode9.2
xcode_project: SwiftyLayouts/SwiftyLayouts.xcodeproj
xcode_scheme: SwiftyLayoutsTests
xcode_sdk: iphonesimulator11.2

branches:
only:
- master

script:
- xcodebuild clean build -project test SwiftyLayouts/SwiftyLayouts.xcodeproj -scheme SwiftyLayoutsTests -destination 'platform=iOS Simulator,name=iPhone 8' -configuration Debug -sdk iphonesimulator11.2 ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES
